spring:
  datasource:
    url: jdbc:mysql://192.168.102.46:3306/demo?serverTimezone=GMT%2B8&useSSL=false
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath: /templates/
    check-template-location: true
    encoding: UTF-8
    suffix: .html
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html



