spring:
  datasource:
    url: jdbc:mysql://192.168.102.46:3306/demo?serverTimezone=GMT%2B8&useSSL=false
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: false



