spring:
  datasource:
    url: jdbc:mysql://192.168.102.46:3306/demo?serverTimezone=GMT%2B8&useSSL=false
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: false

#  # MULTIPART (MultipartProperties)
#  spring.servlet.multipart.enabled=true # Whether to enable support of multipart uploads.
#  spring.servlet.multipart.file-size-threshold=0 # Threshold after which files are written to disk. Values can use the suffixes "MB" or "KB" to indicate megabytes or kilobytes, respectively.
#  #  spring.servlet.multipart.location= # Intermediate location of uploaded files.
#  spring.servlet.multipart.max-file-size=100MB # Max file size. Values can use the suffixes "MB" or "KB" to indicate megabytes or kilobytes, respectively.
#  spring.servlet.multipart.max-request-size=100MB # Max request size. Values can use the suffixes "MB" or "KB" to indicate megabytes or kilobytes, respectively.
#  spring.servlet.multipart.resolve-lazily=false # Whether to resolve the multipart request lazily at the time of file or parameter access.


